(cl:defpackage beginner_tutorials-srv
  (:use )
  (:export
   "ADDTWOINTS"
   "<ADDTWOINTS-REQUEST>"
   "ADDTWOINTS-REQUEST"
   "<ADDTWOINTS-RESPONSE>"
   "ADDTWOINTS-RESPONSE"
   "WORDCOUNT"
   "<WORDCOUNT-REQUEST>"
   "WORDCOUNT-REQUEST"
   "<WORDCOUNT-RESPONSE>"
   "WORDCOUNT-RESPONSE"
  ))

