// Generated by gencpp from file beginner_tutorials/WordCount.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_WORDCOUNT_H
#define BEGINNER_TUTORIALS_MESSAGE_WORDCOUNT_H

#include <ros/service_traits.h>


#include <beginner_tutorials/WordCountRequest.h>
#include <beginner_tutorials/WordCountResponse.h>


namespace beginner_tutorials
{

struct WordCount
{

typedef WordCountRequest Request;
typedef WordCountResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WordCount
} // namespace beginner_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::beginner_tutorials::WordCount > {
  static const char* value()
  {
    return "58903d21a3264f3408d79ba79e9f7c7e";
  }

  static const char* value(const ::beginner_tutorials::WordCount&) { return value(); }
};

template<>
struct DataType< ::beginner_tutorials::WordCount > {
  static const char* value()
  {
    return "beginner_tutorials/WordCount";
  }

  static const char* value(const ::beginner_tutorials::WordCount&) { return value(); }
};


// service_traits::MD5Sum< ::beginner_tutorials::WordCountRequest> should match 
// service_traits::MD5Sum< ::beginner_tutorials::WordCount > 
template<>
struct MD5Sum< ::beginner_tutorials::WordCountRequest>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::WordCount >::value();
  }
  static const char* value(const ::beginner_tutorials::WordCountRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::WordCountRequest> should match 
// service_traits::DataType< ::beginner_tutorials::WordCount > 
template<>
struct DataType< ::beginner_tutorials::WordCountRequest>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::WordCount >::value();
  }
  static const char* value(const ::beginner_tutorials::WordCountRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::beginner_tutorials::WordCountResponse> should match 
// service_traits::MD5Sum< ::beginner_tutorials::WordCount > 
template<>
struct MD5Sum< ::beginner_tutorials::WordCountResponse>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::WordCount >::value();
  }
  static const char* value(const ::beginner_tutorials::WordCountResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::WordCountResponse> should match 
// service_traits::DataType< ::beginner_tutorials::WordCount > 
template<>
struct DataType< ::beginner_tutorials::WordCountResponse>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::WordCount >::value();
  }
  static const char* value(const ::beginner_tutorials::WordCountResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_WORDCOUNT_H
