// Generated by gencpp from file beginner_tutorials/word_count.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_WORD_COUNT_H
#define BEGINNER_TUTORIALS_MESSAGE_WORD_COUNT_H

#include <ros/service_traits.h>


#include <beginner_tutorials/word_countRequest.h>
#include <beginner_tutorials/word_countResponse.h>


namespace beginner_tutorials
{

struct word_count
{

typedef word_countRequest Request;
typedef word_countResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct word_count
} // namespace beginner_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::beginner_tutorials::word_count > {
  static const char* value()
  {
    return "58903d21a3264f3408d79ba79e9f7c7e";
  }

  static const char* value(const ::beginner_tutorials::word_count&) { return value(); }
};

template<>
struct DataType< ::beginner_tutorials::word_count > {
  static const char* value()
  {
    return "beginner_tutorials/word_count";
  }

  static const char* value(const ::beginner_tutorials::word_count&) { return value(); }
};


// service_traits::MD5Sum< ::beginner_tutorials::word_countRequest> should match 
// service_traits::MD5Sum< ::beginner_tutorials::word_count > 
template<>
struct MD5Sum< ::beginner_tutorials::word_countRequest>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::word_count >::value();
  }
  static const char* value(const ::beginner_tutorials::word_countRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::word_countRequest> should match 
// service_traits::DataType< ::beginner_tutorials::word_count > 
template<>
struct DataType< ::beginner_tutorials::word_countRequest>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::word_count >::value();
  }
  static const char* value(const ::beginner_tutorials::word_countRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::beginner_tutorials::word_countResponse> should match 
// service_traits::MD5Sum< ::beginner_tutorials::word_count > 
template<>
struct MD5Sum< ::beginner_tutorials::word_countResponse>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::word_count >::value();
  }
  static const char* value(const ::beginner_tutorials::word_countResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::word_countResponse> should match 
// service_traits::DataType< ::beginner_tutorials::word_count > 
template<>
struct DataType< ::beginner_tutorials::word_countResponse>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::word_count >::value();
  }
  static const char* value(const ::beginner_tutorials::word_countResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_WORD_COUNT_H
