(cl:defpackage beginner_tutorials-msg
  (:use )
  (:export
   "<NUM>"
   "NUM"
   "<TIMERACTION>"
   "TIMERACTION"
   "<TIMERACTIONFEEDBACK>"
   "TIMERACTIONFEEDBACK"
   "<TIMERACTIONGOAL>"
   "TIMERACTIONGOAL"
   "<TIMERACTIONRESULT>"
   "TIMERACTIONRESULT"
   "<TIMERFEEDBACK>"
   "TIMERFEEDBACK"
   "<TIMERGOAL>"
   "TIMERGOAL"
   "<TIMERRESULT>"
   "TIMERRESULT"
  ))

